Implement vaccine cerificate
zinza-d2-training/anhlh-vue pull request #27
Opened 2022-05-27 04:33 UTC by anhzinza

## Summary

## Dependencies

–

## Testing

2022-05-27 08:00 UTC, hungnp194 requested changes
Tham khảo cách tương tác ở màn user info

https://long-react.herokuapp.com/user/info

2022-05-27 08:00 UTC, hungnp194 commented on public/reset.css
> +}
Thêm file này làm gì. Vuetify có sẵn rồi

2022-05-27 08:03 UTC, hungnp194 requested changes

2022-05-27 08:03 UTC, hungnp194 commented on src/views/search/ResultRegister.vue
> +  result!: any[];
Viết type. A đã nhắc nhiều lần là ko xài any rồi

2022-05-27 08:03 UTC, hungnp194 commented on src/views/search/SearchInjections.vue
> +}
Type

2022-05-27 08:03 UTC, hungnp194 commented on src/views/search/CertificateInjection.vue
> +  ];
Type

2022-05-27 08:29 UTC, anhzinza commented on src/views/search/ResultRegister.vue
> +  result!: any[];
e code test logic quên chưa sửa lại

2022-05-29 17:54 UTC, hungnp194 approved these changes

2022-05-29 17:54 UTC, merged